### ISSUE TITLE
Define minimum set of supported locales

### ISSUE THREAD

**Issue by TheJavaGuy** [RokiShopen/RandomDataGenerator#1]
A set of supported locales should be defined. That way we'll know the scope of needed data and what specific functionality will be needed for some locales (for example the way of generating people ID / SSN, bank account numbers etc.)

**Comment by TheJavaGuy** [comment]
After some thinking I propose we support following locales for version 1.0.0:

1. sr-Latn-RS (our native)
2. en-US (most widely used)
3. da-DK (needed for NLS)
4. ca-ES (needed for NLS)

List of all possible locales is at [Oracle's site](http://www.oracle.com/technetwork/java/javase/java8locales-2095355.html) @RokiShopen do you agree with the list?

**Comment by RokiShopen** [comment]
I agree on those four. I will add them now and commit folder structure.

**Comment by RokiShopen** [comment]
Resolved. Added 3 new locales, en_US, da_DK, and ca_ES
