### ISSUE TITLE
Create logic for matching name and sex

### ISSUE THREAD

**Issue by TheJavaGuy** [RokiShopen/RandomDataGenerator#14]
When creating a person's first name we should take into consideration gender - male gender should produce male names and vice versa. I propose to make `enum Gender` and to make that a parameter to the `firstName` method.

**Comment by RokiShopen** [comment]
Added gender parameter in constructor and check is done before generating first name and prefix.

**Comment by TheJavaGuy** [comment]
I have several observations:

1. Gender should be an enum
2. `RandomDataRs` class should not accept gender as a constructor parameter but as a method parameter for methods `namePrefix` and `firstName`. In general, interface `RandomData` should accept that parameter in mentioned methods.
3. It seems we have to separate namePrefixes file to namePrefixesMale and namePrefixesFemale.
4. Method `checkGender` is now not needed.

**Comment by TheJavaGuy** [comment]
This has been merged into master
