### ISSUE TITLE
Static analysis of code

### ISSUE THREAD

**Issue by TheJavaGuy** [RokiShopen/RandomDataGenerator#3]
We must have automatic static analysis of Java code. I suggest we use [Qulice](http://www.qulice.com/). More details can be found [in this blog post](http://www.yegor256.com/2014/08/13/strict-code-quality-control.html). @RokiShopen do you agree with the use of Qulice?

**Comment by TheJavaGuy** [comment]
I tried both Qulice and Checkstyle. Qulice has easier setup but we lose some control with it. For example we can't control which checks will be executed, it is either all or nothing. The only control Qulice offers is to exclude Checkstyle (or PMD, or FindBugs) on some file or directory. If we use Checkstyle alone (or some combination like Checkstyle + PMD + FindBugs) we'll have more to do in configuring everything but we'll have more control.

**Comment by RokiShopen** [comment]
@TheJavaGuy I agree on Qulice, if we start using it now we will have good foundations for the rest of our project. And it would be easier for us to start using it now, I guess it is almost impossible to include it in later stages.

**Comment by TheJavaGuy** [comment]
I added Qulice to pom.xml and started to transform code so that it satisfies Qulice quality policy. We have to solve Git on Windows line ending because Qulice expects all files to have only line feed (\n) as separator.

**Comment by TheJavaGuy** [comment]
We just need to check if this is fixed in Ubuntu also. If it is this issue can be closed.

**Comment by TheJavaGuy** [comment]
This now works in Windows as well as in Ubuntu, closing.
